# Project information
site_name: "mkdocs-versioning"
site_description: "Documentation for mkdocs-versioning plugin"

plugins:
  - search
  - git-revision-date-localized:
      type: datetime
  - mkdocs-versioning:
      version: 0.3.0
      exclude_from_nav: ["images"]

# Repository
repo_name: "mkdocs-versioning"
repo_url: "https://github.com/zayd62/mkdocs-versioning"

theme:
  name: material
  palette:
    scheme: slate
  features:
    - tabs
  icon:
    logo: octicons/versions-24
  favicon: images/favicon.svg
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: "index.md"
  - Detail:
      - How it works: "reference/index.md"
      - Step by Step Example: "reference/step_by_step.md"
      - Config Options: "reference/config_options.md"
      - CLI Options: "reference/cli.md"
  - Version Selector: "../"

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
